# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: docker push -t $(imageName) .
  displayName: 'docker push'

- task: HelmInstaller@0
  displayName: Install Helm 2.9.1
  inputs:
    helmVersion: 2.9.1

- task: HelmDeploy@0
  displayName: helm init --client-only
  inputs:
    command: init
    upgradeTiller: false
    arguments: '--client-only'

- task: HelmDeploy@0
  displayName: helm package
  inputs:
    command: package
    chartPath: 'charts/croc-hunter'

- task: PublishBuildArtifacts@1
  displayName: drop
